### ISSUE TITLE
imageRestriction='none' has no effect?

### ISSUE THREAD

**Issue by debotos** [Norserium/react-mobile-cropper#1]
In the main one https://advanced-cropper.github.io/react-advanced-cropper/#default-cropper imageRestriction is working. But in this one why not?

**Comment by Norserium** [comment]
@debotos, because I've implemented the behavior of croppers that I've seen in some popular mobile applications. They all prevent the leaving of the image, so did I. That's why the prop `imageRestriction` was deleted.

I will consider this issue as the feature request. I assume it's possible to return this prop with two available values: `"none"` and `"stencil"`. 

Other values will be unavailable though.

**Comment by Norserium** [comment]
@debotos, `imageRestriction` prop was added in `0.8.0`. Try it now.

**Comment by Norserium** [comment]
@debotos, any news?

**Comment by Norserium** [comment]
@debotos, I close the issue. Feel free to reopen if you encounter it again.

**Comment by Ruslan-I7** [comment]
There is one thing. when you add just a string, it works but IDE warns you

```js
imageRestriction={ 'none' }
```

![nFciAKmGcL](https://github.com/advanced-cropper/react-mobile-cropper/assets/57489028/becf0b84-bc6d-4c76-a8ad-cdedd8d9f97d)
